// Package bookrender renders a Quarto project along three profile axes.
//
// A render is one topic × format × audience combination (see
// internal/qmcore). What varies per topic is the content: the topic's folder
// tree is flattened into a single .qmd document (see internal/bookmaker)
// that the project's index.qmd includes.
//
// The build documents live in `_build/`, under fixed names. The directory's
// leading underscore keeps Quarto's website scan out of them — the reason
// the files used to be called `_book-build-<topic>.qmd` at the project root.
// The name, however, also excluded them from the project's *inputs*, and
// Quarto only honours `output-dir` and `output-file` for a file it considers
// project input; a render aimed at such a file fell through to the
// standalone document renderer and wrote its output next to the source. An
// underscore-prefixed *directory* achieves the first without the second.
//
// Because the names are fixed, the topic is selected by the profile alone,
// and index.qmd needs one include instead of one per topic.
//
// The package is the render flow of quarto-sorter
// (https://github.com/christophberger/quarto-sorter), lifted out of that
// tool's server so it can be used from the command line as well.
package bookrender

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/cboct/qm/internal/bookmaker"
	"github.com/cboct/qm/internal/qmcore"
)

// BuildDir holds the generated documents, relative to the project root.
const BuildDir = "_build"

// The generated documents. Their names are fixed rather than derived from
// the topic: index.qmd includes `_build/book.qmd` unconditionally, and
// `_quarto-format-slides.yml` renders `_build/slides.qmd` unconditionally.
// Which topic they hold is decided by `qm prepare`, from the profile.
const (
	bookFileName   = "book.qmd"
	slidesFileName = "slides.qmd"
)

// generatedNote heads every generated document. It is also what a build
// file is reduced to when the selection has no topic (a website render):
// index.qmd includes the file whatever the profile, so it has to exist and
// to contribute nothing. A comment is the only content that is safe here —
// a heading would be picked up as the chapter title, which Quarto reads
// before the content filters run.
const generatedNote = "<!-- Generated by `qm prepare`. Do not edit. -->\n"

// BuildDirPath, BookFile, and SlidesFile locate the generated documents.
func BuildDirPath(root string) string { return filepath.Join(root, BuildDir) }
func BookFile(root string) string     { return filepath.Join(BuildDirPath(root), bookFileName) }
func SlidesFile(root string) string   { return filepath.Join(BuildDirPath(root), slidesFileName) }

// Logf receives the render's progress, one line per call, in the format of
// fmt.Printf. A nil Logf discards the output.
type Logf func(format string, args ...any)

func (l Logf) or() Logf {
	if l == nil {
		return func(string, ...any) {}
	}
	return l
}

// FlattenBook turns a content folder into the flat book and slide documents.
func FlattenBook(root, folder string) (*bookmaker.Result, error) {
	dir := filepath.Join(root, folder)
	tree, err := bookmaker.LoadTree(dir, root)
	if err != nil {
		return nil, err
	}
	if tree == nil {
		return nil, fmt.Errorf("%s holds no .qmd files", folder)
	}
	return bookmaker.Flatten(tree, bookmaker.Options{
		ProjectRoot:   root,
		RewriteLinks:  true,
		WrapAudience:  true,
		ExtractSlides: true,
	})
}

// WriteBuild flattens folder into the build documents. An empty folder
// writes the empty build documents, which is what a topic-less (website)
// render needs.
//
// title becomes the slide deck's document title: the deck is a document of
// its own, assembled from divs that carry no title, and pptx needs one for
// its title slide.
func WriteBuild(root, folder, title string, log Logf) error {
	log = log.or()
	if err := os.MkdirAll(BuildDirPath(root), 0o755); err != nil {
		return err
	}
	if folder == "" {
		log("no topic selected; clearing %s/", BuildDir)
		return writeBuildFiles(root, generatedNote, "")
	}
	res, err := FlattenBook(root, folder)
	if err != nil {
		return err
	}
	for _, w := range res.Warnings {
		log("%s: warning: %s", folder, w)
	}
	log("%s: %d pages, %d slides, %d links rewritten",
		folder, res.Pages, res.SlideBlocks, res.Links)
	if res.Slides == "" {
		log("%s: no ::: slide blocks; the deck will be empty", folder)
	}
	return writeBuildFiles(root, generatedNote+res.Content, slideDoc(res.Slides, title))
}

// slideDoc puts a title on the extracted slide content, or returns the
// empty document when there are no slides.
func slideDoc(slides, title string) string {
	if strings.TrimSpace(slides) == "" {
		return ""
	}
	head := generatedNote
	if title != "" {
		head += "---\ntitle: " + yamlQuote(title) + "\n---\n\n"
	}
	return head + slides
}

// yamlQuote wraps a scalar in single quotes, YAML's escape for one.
func yamlQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// writeBuildFiles writes both documents, replacing whatever the previous
// render left. An empty deck still produces a file: the slides format
// renders `_build/slides.qmd` by name and fails if it is missing.
func writeBuildFiles(root, book, slides string) error {
	if slides == "" {
		slides = generatedNote
	}
	if err := os.WriteFile(BookFile(root), []byte(book), 0o644); err != nil {
		return err
	}
	return os.WriteFile(SlidesFile(root), []byte(slides), 0o644)
}

// Options is one render request: the matrix of selections to run, in order.
type Options struct {
	// Root is the project root; Quarto is run from there.
	Root string
	// Selections are the topic × format × audience combinations to render,
	// one `quarto render` each.
	Selections []qmcore.Selection
	// Clean empties the output directories of the selected formats before
	// the first render. Quarto's own cleaning is switched off for every run
	// (see quarto below), so without this a topic deleted from the project
	// keeps its stale output forever.
	Clean bool
	// DryRun prints the quarto invocations without running them.
	DryRun bool
}

// Run renders every selection, carrying on after a failure so that one
// broken combination does not hide the others.
func Run(o Options, log Logf) error {
	log = log.or()
	if len(o.Selections) == 0 {
		return fmt.Errorf("nothing selected to render")
	}
	if o.Clean && !o.DryRun {
		if err := cleanOutputDirs(o.Root, o.Selections, log); err != nil {
			return err
		}
	}
	failed := 0
	for _, sel := range o.Selections {
		if err := quarto(o.Root, sel, o.DryRun, log); err != nil {
			log("%s: %v", sel, err)
			failed++
		}
	}
	if failed > 0 {
		return fmt.Errorf("%d of %d render(s) failed", failed, len(o.Selections))
	}
	log("done: %d render(s)", len(o.Selections))
	return nil
}

// QuartoCommand is the executable that renders; tests and unusual
// installations replace it.
var QuartoCommand = "quarto"

// quarto runs one `quarto render` for a selection.
//
// The three profiles go into a single --profile argument: each contributes a
// different part of one configuration — the topic the content, the format
// the output directory and the file name pattern, the audience the
// variables the file name is composed from — so dropping any of them leaves
// Quarto with an incomplete project.
//
// No input file is named: the project is rendered as a whole, and its
// index.qmd includes the flattened topic. No --to either; the formats are
// the ones the format profile declares, and Quarto renders them all in one
// pass. No --output or --output-dir, leaving the output paths to the
// configuration, which is the point of the whole arrangement.
//
// --no-clean is not optional: several topics and audiences share one output
// directory, so a cleaning run would delete what the run before it produced.
// Quarto has no configuration key for this, hence Options.Clean.
func quarto(root string, sel qmcore.Selection, dryRun bool, log Logf) error {
	args := []string{"render", "--profile", sel.String(), "--no-clean"}
	log("$ %s %s", QuartoCommand, strings.Join(args, " "))
	if dryRun {
		return nil
	}

	cmd := exec.Command(QuartoCommand, args...)
	cmd.Dir = root // profiles and project config are found from here
	w := &lineWriter{log: log}
	cmd.Stdout, cmd.Stderr = w, w

	err := cmd.Run()
	w.flush()
	if err != nil {
		return fmt.Errorf("quarto render --profile %s: %w", sel, err)
	}
	return nil
}

// cleanOutputDirs empties the output directory of every format in the
// matrix once, before the first render. Doing it here rather than letting
// Quarto do it per run is what makes several topics able to share a
// directory.
func cleanOutputDirs(root string, sels []qmcore.Selection, log Logf) error {
	seen := map[string]bool{}
	for _, sel := range sels {
		p, err := qmcore.LoadProfile(root, qmcore.AxisFormat.ProfileName(sel.Format))
		if err != nil {
			return err
		}
		dir, err := qmcore.FormatOutputDir(p)
		if err != nil {
			return err
		}
		if dir == "" || seen[dir] {
			continue
		}
		seen[dir] = true
		abs, err := qmcore.ProjectPath(root, dir)
		if err != nil {
			return err
		}
		log("cleaning %s/", dir)
		if err := os.RemoveAll(abs); err != nil {
			return err
		}
	}
	return nil
}

// lineWriter feeds a command's output into the log line by line.
type lineWriter struct {
	log Logf
	buf bytes.Buffer
}

func (w *lineWriter) Write(p []byte) (int, error) {
	w.buf.Write(p)
	for {
		line, err := w.buf.ReadString('\n')
		if err != nil {
			// Keep the partial line for the next write.
			w.buf.Reset()
			w.buf.WriteString(line)
			return len(p), nil
		}
		w.log("%s", strings.TrimRight(line, "\r\n"))
	}
}

// flush emits whatever the command left without a trailing newline.
func (w *lineWriter) flush() {
	if rest := strings.TrimRight(w.buf.String(), "\r\n"); rest != "" {
		w.log("%s", rest)
	}
	w.buf.Reset()
}

// ContentFolders lists the project's content folders by name: the
// first-level folders that hold Quarto content. Media folders, dot and
// underscore entries, and folders with a Quarto project config of their own
// are not content folders. It is what a topic profile's `qm: folder:` may
// name.
func ContentFolders(root string) []string {
	dirs, err := bookmaker.BookFolders(root)
	if err != nil {
		return nil
	}
	names := make([]string, 0, len(dirs))
	for _, d := range dirs {
		names = append(names, filepath.Base(d))
	}
	return names
}
